import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@copilotkit/react-ui/styles.css";
import { CopilotKit } from "@copilotkit/react-core";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const publicApiKey = process.env.NEXT_PUBLIC_COPILOT_API_KEY;

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<CopilotKit
					publicApiKey={publicApiKey}
					runtimeUrl="/api/copilotkit"
					showDevConsole={process.env.NODE_ENV === "development"}
				>
					{children}
				</CopilotKit>
			</body>
		</html>
	);
}
